on:
  push:

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v3
    - name: install test requirements and run pylint
      run: |
        pip install -r test-requirements.txt
        pylint src/python/EddieMUD
